%{?!ros_distro:%global ros_distro rolling}
%global pkg_name foxglove_sdk_vendor
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-rolling-foxglove-sdk-vendor
Version:        0.3.0
Release:        1%{?dist}
Summary:        ROS %{pkg_name} package

License:        MIT
URL:            https://docs.foxglove.dev/docs/sdk
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
Vendor package that fetches prebuilt Foxglove SDK archives and exposes the
headers and libfoxglove.a static library to ROS 2 workspaces.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
Vendor package that fetches prebuilt Foxglove SDK archives and exposes the
headers and libfoxglove.a static library to ROS 2 workspaces.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
Vendor package that fetches prebuilt Foxglove SDK archives and exposes the
headers and libfoxglove.a static library to ROS 2 workspaces.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DAMENT_PREFIX_PATH="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C %{__cmake_builddir} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
CTEST_OUTPUT_ON_FAILURE=1 \
    %cmake_build $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Fri Aug 21 2026 Jordan Lack <jlack1987@gmail.com> - 0.3.0-1
- Autogenerated by Bloom

* Tue Apr 28 2026 Jordan Lack <jlack1987@gmail.com> - 0.2.0-3
- Autogenerated by Bloom

* Tue Apr 21 2026 Jordan Lack <jlack1987@gmail.com> - 0.2.0-2
- Autogenerated by Bloom
